feedback/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^post/(?P<pk>\d+)/$', views.post_detail, name='thanks'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('feedback.urls')),
]

feedback/models.py
from django.db import models
from django.utils import timezone


class Post(models.Model):
    ANIMALS = 'AN'
    FLOWERS = 'FL'
    BEE = 'BE'
    FISH = 'FI'
    CATEGORY_CHOICES = (
        (ANIMALS, 'Животноводство'),
        (FLOWERS, 'Растениеводство'),
        (BEE, 'Пчеловодство'),
        (FISH, 'Рыболовство'),
    )
    category = models.CharField(max_length=40,
                                      choices=CATEGORY_CHOICES)

    author = models.ForeignKey('auth.User', on_delete=models.CASCADE, blank=True, null=True)
    fio = models.CharField(max_length=200)
    phone = models.CharField(max_length=13)
    email = models.EmailField()
    comment = models.TextField(max_length=600)

    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.fio

feedback/forms.py
from django import forms

from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('fio', 'phone', 'email', 'category', 'comment')

feedback/views.py
from django.shortcuts import render
from .models import Post
from django.utils import timezone
from .forms import PostForm
from django.http import HttpResponse
from django.shortcuts import redirect
from django.shortcuts import render, get_object_or_404

# Create your views here.
def post_list(request):
    posts = Post.objects.order_by('-published_date')
    return render(request, 'feedback/post_list.html', {'posts': posts})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'feedback/thanks.html', {'post': post})

def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            # post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('thanks', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'feedback/post_edit.html', {'form': form})

feedback/templates/feedback/post_edit.html
<!DOCTYPE HTML>
{% load staticfiles %}
<html>
	<head>
		<title>Аграрные мастер-классы для детей</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
		<link rel="stylesheet" href="{% static 'css/main.css' %}">
		<!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->
		<!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->
	</head>
	<body class="landing">

		<!-- Header -->
		{% if user.is_authenticated %}
			<header id="header" class="alt">
				<a href="{% url 'post_list' %}">Заявки</a>
			</header>
		{% endif %}


		<!-- Banner -->
			<section id="banner">
				<span class="image"><img src="{% static "images/leaves.png" %}" alt=""/></span>
				<h2>Аграрные мастер-классы для детей</h2>

			</section>

			<!-- Two -->
			<section id="two" class="wrapper special">
				<div class="inner">
					<header class="major narrow">
						<p>Современных детей трудно увлечь чем-либо, тем более удивить и заинтересовать на длительный период времени. Оригинальные мастер классы, представленные у нас, специально созданы для организации интересного детского досуга за пределами городской среды!
В зависимости от интересов и увлечений Вашего ребенка Вы можете выбрать различные мастер-классы сельскохозяйственной направленности.<br>
В настоящее время проводятся следующие виды мастер-классов:<br>
<br>
Животноводство<br>
Растениеводство<br>
Пчеловодство<br>
Рыболовство<br>
<br>

Все мастер-классы проводятся на базе ОАО «АГРОФИРМА «СРЕДНЯЯ ВОЛГА», что находится в 11 километрах от городаЧебоксары, по адресу: 429526, Чувашская Республика - Чувашия, Чебоксарский район, с Хыркасы, ул Ресторанная, д 4.
</p>
					</header>
				</div>
			</section>

		<!-- One -->
			<section id="one" class="wrapper style1">
				<div class="inner">
					<article class="feature left">
						<span class="image"><img src="{% static "images/pic01.jpg" %}" alt=""/></span>
						<div class="content">
							<h2>Животноводство</h2>
							<p>Животноводство – это отрасль сельского хозяйства, специализирующаяся на разведении животных. Основные виды деятельности мастер-класса по животноводству связаны с выполнением работ по уходу за животными на фермах и сельскохозяйственных предприятиях. Данный мастер-класс способствует привитию любви к животным. В ходе мастер-класса Ваш ребёнок научится кормить телят, свиней, кур, кроликов и других домашних животных, узнает, как пасут коров и овец.</p>
							</ul>
						</div>
					</article>
					<article class="feature right">
						<span class="image"><img src="{% static "images/pic02.jpg" %}" alt=""/></span>
						<div class="content">
							<h2>Растениеводство</h2>
							<p-e>Растениеводство — отрасль сельского хозяйства, занимающаяся возделыванием культурных растений. Основная деятельность мастера-класса по растениеводству связана с выполнением работ по выращиванию и уходу за растениями.
В ходе мастер-класса Ваш ребёнок научится выполнять работы по:
<ul>
	<li>обработке почвы</li>
	<li>производству рассады и посадочного материала</li>
	<li>уходу за посевами и посадками сельскохозяйственных культур</li>
	<li>проведению мероприятий по защите растений от вредителей, сорняков</li>
	<li>сборке урожая и транспортировке к местам хранения</li>
</ul>
</p-e>

						</div>
					</article>
					<article class="feature left">
						<span class="image"><img src="{% static "images/pic03.jpg" %}" alt=""/></span>
						<div class="content">
							<h2>Пчеловодство</h2>
							<p>Пчеловодство — отрасль сельского хозяйства, которая занимается разведением медоносных пчёл для получения мёда, пчелиного воска и других продуктов. В ходе данного мастер-класса Ваш ребёнок узнает, как получают мёд, научится кормить пчёл, ухаживать за пчелиным улеем, собирать полученный мёд, а также сможет полакомиться им.</p>
						</div>
					</article>
					<article class="feature right">
						<span class="image"><img src="{% static "images/pic04.jpg" %}" alt=""/></span>
						<div class="content">
							<h2>Рыболовство</h2>
							<p>Рыболовство — занятие выуживанием рыбы из водоёма с целью прокорма или просто для развлечения. Данный мастер-класс привьёт Вашему ребёнку такое качество, как терпение. Ведь это одно из самых важных качеств в процессе рыбалки. В ходе мастер-класса он научится различным техникам ловли рыбы, узнает, какие виды рыб обитают в водоёмах нашей местности.</p>
						</div>
					</article>
				</div>
			</section>




		<!-- Three -->
			<section id="three" class="wrapper style3 special">
				<div class="inner">
					<header class="major narrow	">
						<h3>Мастер-классы проводятся по предварительной записи по мере формирования групп.</h3>
<h1>Программа мероприятия:
	<br>

10.00 Встреча и регистрация участников мастер-классов<br>
10.30-12.00 Экскурсия по ОАО «АГРОФИРМА «СРЕДНЯЯ ВОЛГА»<br>
12.00-13.00 Обед<br>
13.00-16.00 Мастер-классы по выбранным направлениям<br>
17.00-18.00 Ужин<br></h1>
<br>
<p>Стоимость мероприятия составляет 1500 рублей.<br>
Все интересующие вопросы вы можете задать по тел.: +7 906 388 84 04</p>
					</header>

				</div>
			</section>




			<!-- Four -->
				<section id="four" class="wrapper style2 special">
					<div class="inner">
						<header class="major narrow">
							<h2>Записаться на мастер-класс</h2>
							<p>Это легко и просто :)</p>
						</header>


						<form method="POST" class="post-form">{% csrf_token %}
							<div class="12u$">
							<label for="fio">ФИО: </label>
    					<input id="fio" type="text" name="fio" value="{{ fio }}">
							</div>

							<label for="phone">Телефон: </label>
    					<input id="phone" type="text" name="phone" value="{{ phone }}">

							<label for="email">Почта: </label>
    					<input id="email" type="email" name="email" value="{{ email }}">

							<label for="email">Мастер-класс: </label>
							<select name="category" required="" id="id_category">
						  <option value="" selected="">---------</option>
						  <option value="AN">Животноводство</option>
						  <option value="FL">Растениеводство</option>
						  <option value="BE">Пчеловодство</option>
						  <option value="FI">Рыболовство</option>
						  </select>

							<label for="comment">Комментарий: </label>
    					<input id="comment" type="text" name="comment" value="{{ comment }}">
						<label for="submit"> </label>
	        	<button type="submit" class="save btn btn-default">Отправить</button>
	    			</form>




					</div>
				</section>

		<!-- Footer -->
			<footer id="footer">
				<div class="inner">

					<ul class="copyright">
						<li>RTC.TRAVEL</a></li>
					</ul>
				</div>
			</footer>

		<!-- Scripts -->
			<script src="js/jquery.min.js"></script>
			<script src="js/skel.min.js"></script>
			<script src="js/util.js"></script>
			<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
			<script src="js/main.js"></script>

	</body>
</html>

feedback/templates/feedback/post_list.html
<!DOCTYPE HTML>
{% load staticfiles %}
<html>
	<head>
		<title>Заявки</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
		<link rel="stylesheet" href="{% static 'css/main.css' %}">
		<!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->
		<!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->
	</head>
	<body>

		<!-- Header -->
			<header id="header">
				<h1><a href="{% url 'post_new' %}">Мастер-классы</a></h1>
			</header>


		<!-- Main -->
			<section id="main" class="wrapper">
				<div class="container">




						 {% for post in posts %}
			    		<div>
							<h1><a href="">{{ post.fio }}</a></h1>
			        <p-с>Телефон: {{ post.phone }}</p-с><br>
							<p-с>E-mail: {{ post.email }}</p-с><br>
							<p-с>Категория: {{ post.get_category_display }}</p-с><br>
							<p-с>Дата заявки: {{ post.published_date }}</p-с><br>
			        <p-с>Комментарий: {{ post.comment|linebreaksbr }}</p-с><br>
							<br>
							<br>
			    </div>
					{% endfor %}



				</div>
			</section>

		<!-- Footer -->
			<footer id="footer">
				<div class="inner">

					<ul class="copyright">
						<li>RTC.TRAVEL</a></li>
					</ul>
				</div>
			</footer>

		<!-- Scripts -->
			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/skel.min.js"></script>
			<script src="assets/js/util.js"></script>
			<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
			<script src="assets/js/main.js"></script>

	</body>
</html>

feedback/templates/feedback/thanks.html
<!DOCTYPE HTML>
{% load staticfiles %}
<html>
	<head>
		<title>Заявки</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
		<link rel="stylesheet" href="{% static 'css/main.css' %}">
		<!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->
		<!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->
	</head>
	<body>


      <section id="three" class="wrapper style3 special">
        <div class="inner">
          <header class="major narrow	">
            <h2>Ваша заявка принята, мы свяжемся с Вами в ближайшее время!</h2>
            <p><a href="{% url 'post_new' %}">Вернуться назад</a></p>
          </header>

        </div>
      </section>

		<!-- Footer -->
			<footer id="footer">
				<div class="inner">

					<ul class="copyright">
						<li>RTC.TRAVEL</a></li>
					</ul>
				</div>
			</footer>

		<!-- Scripts -->
			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/skel.min.js"></script>
			<script src="assets/js/util.js"></script>
			<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
			<script src="assets/js/main.js"></script>

	</body>
</html>